import { ArrowDown, ArrowUpRight, BookOpen, MapPin, Play } from 'lucide-react';
import { Link } from '@/i18n/navigation';

export default function StartHere({ locale }: { locale: string }) {
  const en = locale === 'en';
  return <section aria-labelledby="start-here-title" className="border-y border-border bg-deep/70 py-10 sm:py-14"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 font-mono text-[10px] uppercase tracking-[0.25em] text-accent">{en ? 'A PERSONAL JOURNAL · @KAUAARTX' : 'UM DIÁRIO PESSOAL · @KAUAARTX'}</p><h2 id="start-here-title" className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">{en ? 'New here? Start with a story.' : 'Chegou agora? Comece por uma história.'}</h2></div><Link href="/about" className="inline-flex items-center gap-2 text-sm text-accent-bright">{en ? 'Meet Kauã' : 'Conheça o Kauã'}<ArrowUpRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-3">
    <a href="#canal" className="group rounded-2xl border border-accent/30 bg-accent/10 p-6 transition-colors hover:bg-accent/20"><div className="mb-6 flex items-center justify-between text-accent-bright"><Play size={22}/><span className="font-mono text-xs">01</span></div><h3 className="text-lg font-semibold text-foreground">{en ? 'Watch the channel' : 'Acompanhe em vídeo'}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{en ? 'Stories, discoveries and the journey as it happens.' : 'Histórias, descobertas e a jornada acontecendo.'}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-accent-bright">{en ? 'Go to the channel section' : 'Ir para a área do canal'}<ArrowDown size={14}/></span></a>
    <Link href="/viagens/oxford" className="group rounded-2xl border border-border bg-surface p-6 transition-colors hover:bg-surface-elevated"><div className="mb-6 flex items-center justify-between text-accent-bright"><MapPin size={22}/><span className="font-mono text-xs">02</span></div><h3 className="text-lg font-semibold text-foreground">{en ? 'My chapter in Oxford' : 'Meu capítulo em Oxford'}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{en ? 'The place I call home in this chapter, brought together in one story.' : 'O lugar onde moro nesta fase, reunido em uma história.'}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-accent-bright">{en ? 'Explore this chapter' : 'Explorar este capítulo'}<ArrowUpRight size={14}/></span></Link>
    <Link href="/blog" className="group rounded-2xl border border-border bg-surface p-6 transition-colors hover:bg-surface-elevated"><div className="mb-6 flex items-center justify-between text-accent-bright"><BookOpen size={22}/><span className="font-mono text-xs">03</span></div><h3 className="text-lg font-semibold text-foreground">{en ? 'Take a moment to read' : 'Leia com calma'}</h3><p className="mt-2 text-sm leading-relaxed text-foreground-muted">{en ? 'Notes and stories to explore at your own pace.' : 'Registros e histórias para explorar no seu ritmo.'}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-accent-bright">{en ? 'Open the journal' : 'Abrir o diário'}<ArrowUpRight size={14}/></span></Link>
  </div></div></section>;
}
